### ISSUE TITLE
MMS example

### ISSUE THREAD

**Issue by metalnouh** [keyvdir/pyiec61850#1]
Please do you have an example of MMS server

**Comment by keyvdir** [comment]
> Please do you have an example of MMS server

did you mean this server example? 
https://github.com/keyvdir/pyiec61850/blob/master/server.py

or you can check other examples of the official repository for libIEC61850
https://github.com/mz-automation/libiec61850/tree/v1.4/examples

**Comment by metalnouh** [comment]
please in need examples using python

**Comment by darkjhesus** [comment]
Could you share the python library, I have problems trying to compile in python 3.6 on Windows 10. When I impot the module I get the next error: ImportError: DLL load failed: No se puede encontrar el módulo especificado

Could you help me?

**Comment by keyvdir** [comment]
> please in need examples using python

this is a simple example of an MMS server using python from creating the model until update the value of each data attribute. https://github.com/keyvdir/pyiec61850/blob/master/server.py



> Could you share the python library, I have problems trying to compile in python 3.6 on Windows 10. When I impot the module I get the next error: ImportError: DLL load failed: No se puede encontrar el módulo especificado
> 
> Could you help me?

You need to build the library for Python 3.6, please check the updated version of the readme file.  Don't forget to re-do from the scratch, delete all the previously installed files. https://github.com/keyvdir/pyiec61850/blob/master/README.md

**Comment by darkjhesus** [comment]
keyvdir, I followed your steps but I get the next error:

windows Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)

I am trying to install in python 36 windows 10 64 bits. Maybe some aditional recomendation.?

**Comment by keyvdir** [comment]
> keyvdir, I followed your steps but I get the next error:
> 
> windows Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
> 
> I am trying to install in python 36 windows 10 64 bits. Maybe some aditional recomendation.?

change with the directory of ur python in this line `cmake -DBUILD_PYTHON_BINDINGS=ON -DPYTHON_EXECUTABLE=/usr/bin/python3 .` . Maybe for windows, it would be stored in C:\Users\(your username)\AppData\Local\Programs\Python\Python36

**Comment by darkjhesus** [comment]
Dear keyvdir, at the firs time I get the next error:

AORTIZ@aortiz MINGW64 ~/libiec61850/pyiec61850 (v1.4)
$ cmake -Wno-dev -DBUILD_PYTHON_BINDINGS=ON -DPYTHON_EXECUTABLE=C:/python38
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.25.28614.0
-- The CXX compiler identification is MSVC 19.25.28614.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found SWIG: C:/swigwin-4.0.1/swig.exe (found version "4.0.1")
-- Found PythonInterp: C:/Python38
-- Found PythonLibs: optimized;C:/Python38/libs/python38.lib;debug;C:/Python38/libs/python38_d.lib (found version "3.8.2")
CMake Error at CMakeLists.txt:41 (install):
  install FILES given no DESTINATION!

CMake Error at CMakeLists.txt:42 (install):
  install TARGETS given no LIBRARY DESTINATION for module target "_iec61850".

-- Configuring incomplete, errors occurred!
See also "C:/Users/aortiz.SUBTRANSMISION/libiec61850/pyiec61850/CMakeFiles/CMakeOutput.log".

**************************************************************************************************************************************************************************************************************
After many test finally I could install tje library, but when I import from python the iec61850 library I get the next error:

Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import iec61850
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import iec61850
ModuleNotFoundError: No module named 'iec61850'

**************************************************************************************************************************************************************************************************************
The las lines when apparently I could install the module are the next:

AORTIZ@aortiz MINGW64 ~/libiec61850/pyiec61850 (v1.4)
$ cmake -Wno-dev -DBUILD_PYTHON_BINDINGS=ON -DPYTHON_EXECUTABLE=C:/Python38/python.exe -DPYTHON_LIBRARY=C:/Python38/libs/python38.lib
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.25.28614.0
-- The CXX compiler identification is MSVC 19.25.28614.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found SWIG: C:/swigwin-4.0.1/swig.exe (found version "4.0.1")
-- Found PythonInterp: C:/Python38/python.exe (found version "3.8.2")
-- Found PythonLibs: optimized;C:/Python38/libs/python38.lib;debug;C:/Python38/libs/python38_d.lib (found suitable exact version "3.8.2")
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_PYTHON_BINDINGS

-- Build files have been written to: C:/Users/aortiz.SUBTRANSMISION/libiec61850/pyiec61850

**************************************************************************************************************************************************************************************************************
  I dont know what is wrong with the file generation. Help me please.

**Comment by keyvdir** [comment]
I haven't tried my codes in the Windows environment. Let me try and catch you up later. The error lines indicate that the python library of iec61850 is not installed yet. If it's successfully installed, inside the libiec61850/pyiec61850 folder, you'll have an iec61850.py file. Also, make sure that you already installed SWIG.

**Comment by darkjhesus** [comment]
I will be attentive if you post some solution. Thanks a lot for your support.

**Comment by darkjhesus** [comment]
Dear, after many tryies finally I could install iec61850 library, but when call the module in python the next error appear in console:
import iec61850
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import iec61850
  File "C:\Python38\lib\site-packages\iec61850.py", line 15, in <module>
    import _iec61850
ImportError: DLL load failed while importing _iec61850: No se puede encontrar el módulo especificado.

Maybe do you know why these problem is?


![Sin título](https://user-images.githubusercontent.com/18389488/80895053-5c58ba80-8ca6-11ea-95b6-f32630d6d445.png)

**Comment by darkjhesus** [comment]
Maybe do you have some example to read comtrade files from ied?

**Comment by metalnouh** [comment]
please you have any a server controls example
i couldn't use control model handling , is it not defined
